We consider the following LP:

$$
(P)\begin{array}{rl}
\max & 3x_1+5x_2\\
s.t.   & x_1+x_3=4\\
       & 2x_2+x_4=12\\
       & 3x_1+2x_2+x_5=18\\
       & x_1,x_2,x_3,x_4,x_5 \geq 0\\
\end{array}
$$

The feasible domain can be plotted as 

<img src="figure001.png">
<center>
The feasible domain in $\mathbb{R}^2$
</center>

All possible basic feasible solutions are computed.
<center>
    Extreme Points in $\mathbb{R}^{5}$
</center>
$$
\begin{array}{lll}
(0,0,4,12,18), &x_1=0, x_2=0\\
(0,6,4,0,6),   &x_1=0, x_4=0\\
(0,9,4,-6,0),  &x_1=0, x_5=0\\
(2,6,2,0,0),   &x_4=0, x_5=0\\
(4,0,0,12,6),  &x_2=0, x_3=0\\
(4,3,0,12,0),  &x_3=0, x_5=0\\
(4,6,0,0,-6),  &x_3=0, x_4=0\\
(6,0,-2,6,0),  &x_2=0, x_5=0\\
\end{array}
$$

The iteration of simplex method is given by 
$$
\begin{array}{lll}
(4,0,0,12,6),  & x_2=0, x_3=0\\
&\Downarrow\\
(4,3,0,12,0),  & x_3=0, x_5=0\\
&\Downarrow\\
(2,6,2,0,0),   & x_4=0, x_5=0\\
\end{array}
$$

<img src="table004003.png">
<center>
</center>

<img src="table004004.png">
<center>
</center>

<img src="table004005.png">
<center>
</center>

<img src="table004006.png">
<center>
</center>

Original Form:
$$
\begin{array}{cccccccccccccccccc}
z:   & z & - & 3x_1& - & 5x_2 &   &     &   &     &   &     & = & 0\\
x_3: &   &   &  x_1&   &      & + & {x_3} &   &     &   &     & = & 4\\
x_2: &   &   &     & + & {2x_2} &   &     & + & x_4 &   &     & = & 12 \\
x_5: &   &   & 3x_1& + & {2x_2} &   &     &   &     & + & {x_5} & = & 18\\
\end{array}
$$

Simplified Form
$$
\begin{array}{cccccccccccccccccc}
z:   & {z} & - & 3x_1& +  & {0x_2} & + &{0x_3} & + & \displaystyle\frac{5}{2}x_4    & + & {0x_5} & = & 30\\
x_3: & {0z}&   &  x_1& +  & {0x_2} & + &{ x_3} &   &                      & + & {0x_5} & = & 4\\
x_2: & {0z}&   &     & +  & {x_2 } & + &{0x_3} & + & \displaystyle\frac{1}{2}x_4    & + & {0x_5} & = & 6 \\
x_5: & {0z}&   & 3x_1& +  & {0x_2} & + &{0x_3} & -  & x_4                 & + & {x_5 }& = & 6\\
\end{array}
$$

<img src="table004007.png">
<center>
</center>

Suppose $x_1$ and $x_4$ are set to zero. Want to know the values of $z$, $x_2$, $x_3$, $x_5$.

Original Form:
$$
\begin{array}{cccccccccccccccccc}
z:   & z & - & 3x_1& - & 5x_2 &   &     &   &     &   &     & = & 0\\
x_3: &   &   &  x_1&   &      & + & {x_3} &   &     &   &     & = & 4\\
x_2: &   &   &     & + & {2x_2} &   &     & + & x_4 &   &     & = & 12 \\
x_5: &   &   & 3x_1& + & {2x_2} &   &     &   &     & + & {x_5} & = & 18\\
\end{array}
$$
Simplified Form
$$
\begin{array}{cccccccccccccccccc}
z:   & {z} & - & 3x_1& +  & {0x_2} & + &{0x_3} & + & \displaystyle\frac{5}{2}x_4    & + & {0x_5} & = & 30\\
x_3: & {0z}&   &  x_1& +  & {0x_2} & + &{ x_3} &   &                      & + & {0x_5} & = & 4\\
x_2: & {0z}&   &     & +  & {x_2 } & + &{0x_3} & + & \displaystyle\frac{1}{2}x_4    & + & {0x_5} & = & 6 \\
x_5: & {0z}&   & 3x_1& +  & {0x_2} & + &{0x_3} & -  & x_4                 & + & {x_5 }& = & 6\\
\end{array}
$$

<ul>
  <li> These two systems of linear equations are coincided.
  <li> The objective value $30$ is directly obtained from the second system.
  <li> We can observe how we reduce the value of $z$.
  <li> If we fix $x_4$ by $0$ and increase $x_1$, then there is a convenient way for updating the value $x_1$.
      </ul>

Matrix Representation for Tabular Form

Let
$$
\bar{A}=
\left[
\begin{array}{ccc}
1 & -{\bf c}^t & 0\\
{\bf 0} & A & {\bf b}\\
\end{array}
\right]
=\left[
\begin{array}{ccccccc}
1 & -3 & -5 & 0 & 0 & 0 & 0  \\
0 & 1  & 0  & 1 & 0 & 0 & 4  \\
0 & 0  & 2  & 0 & 1 & 0 & 12 \\
0 & 3  & 2  & 0 & 0 & 1 & 18 \\
\end{array}
\right]\hbox{ and }
\bar{B}=\left[
\begin{array}{ccc}
1 & -{\bf c}_{B}^t \\
{\bf 0} & B\\
\end{array}
\right].
$$
Set
$$
%\hbox{ and }
B=\left[
\begin{array}{cccc}
 1 & 0 & 0 \\
 0 & 2 & 0 \\
 0 & 2 & 1 \\
\end{array}
\right]
\hbox{ and }
B^{-1}=\left[
\begin{array}{cccc}
 1 & 0 & 0 \\
 0 & 1/2 & 0 \\
 0 & -1 & 1 \\
\end{array}
\right].
$$
Then
$$
\bar{B}^{-1}=
\left[
\begin{array}{ccc}
1 & {\bf c}_{B}^tB^{-1} \\
{\bf 0} & B^{-1}\\
\end{array}
\right]=
\left[
\begin{array}{cccc}
1  & 0 & 5/2& 0 \\
0  & 1 & 0 & 0 \\
0  & 0 & 1/2 & 0 \\
0  & 0 & -1 & 1 \\
\end{array}
\right].
$$

$$
\bar{B}^{-1}\bar{A}=
\left[
\begin{array}{ccc}
1 & {\bf c}_{B}^tB^{-1} \\
{\bf 0} & B^{-1}\\
\end{array}
\right]
\left[
\begin{array}{ccc}
1 & -{\bf c}^t & 0\\
{\bf 0} & A & {\bf b}\\
\end{array}
\right]
=
\left[
\begin{array}{ccc}
1 & -{\bf c}^t+{\bf c}_{B}^{t}B^{-1}A & {\bf c}_{B}^{t}B^{-1}{\bf b}\\
{\bf 0} & B^{-1}A & B^{-1}{\bf b}\\
\end{array}
\right]
$$
$$
=\left[
\begin{array}{ccccccc}
1 & -3 & 0 & 0 & 5/2 & 0 & 30  \\
0 & 1  & 0  & 1 & 0 & 0 & 4  \\
0 & 0  & 1  & 0 & 1/2 & 0 & 6 \\
0 & 3  & 0  & 0 & -1 & 1 & 6 \\
\end{array}
\right]({\hbox{Please verify it by yourself once}})
$$

In [10]:
import numpy as np
import sympy

<img src="table004003.png">
<center>
</center>

$$
(P)\begin{array}{rl}
\max & 3x_1+5x_2\\
s.t.   & x_1+x_3=4\\
       & 2x_2+x_4=12\\
       & 3x_1+2x_2+x_5=18\\
       & x_1,x_2,x_3,x_4,x_5 \geq 0\\
\end{array}
$$

Declare a numpy array c=np.zeros((n,1)) to store the cost vector 
$$
\left[\begin{array}{c}
3\\
5\\
0\\
0\\
0\\
\end{array}
\right]
$$

In [11]:
m=3
b=np.zeros((m,1))
b[0,0]=4
b[1,0]=12
b[2,0]=18
print(b)

[[ 4.]
 [12.]
 [18.]]


Declare a numpy array b=np.zeros((n,1)) to store the right-hand-side vector  
$$
\left[\begin{array}{c}
1 & 0 & 1 & 0 & 0\\
0 & 2 & 0 & 1 & 0\\
3 & 2 & 0 & 0 & 1\\
\end{array}
\right]
$$

In [12]:
m,n=3,5
A=np.zeros((m,n))
A[0,0]=1
A[1,0]=0
A[2,0]=3

A[0,1]=0
A[1,1]=2
A[2,1]=2

A[0,2]=1
A[1,2]=0
A[2,2]=0

A[0,3]=0
A[1,3]=1
A[2,3]=0

A[0,4]=0
A[1,4]=0
A[2,4]=1

print(A)

[[1. 0. 1. 0. 0.]
 [0. 2. 0. 1. 0.]
 [3. 2. 0. 0. 1.]]


In [13]:
A=np.array([[1,0,1,0,0],[0,2,0,1,0],[3,2,0,0,1]]) #用list 輸入再轉為np.array
print(A)

[[1 0 1 0 0]
 [0 2 0 1 0]
 [3 2 0 0 1]]


Declare a numpy array A=np.zeros((m,n)) to store the cost vector 
$$
\left[\begin{array}{c}
3\\
5\\
0\\
0\\
0\\
\end{array}
\right]
$$

In [14]:
n=5
c=np.zeros((n,1))
c[0,0]=3
c[1,0]=5
c[2,0]=0
c[3,0]=0
c[4,0]=0
print(c)

[[3.]
 [5.]
 [0.]
 [0.]
 [0.]]


In order to obtain the matrix in 
<img src="table004003.png">
Use $A$, $b$, $c$ to construct the augmented matrix:
$$
\left[
\begin{array}{ccccccc}
1 & -3 & -5 & 0 & 0 & 0 & 0  \\
0 & 1  & 0  & 1 & 0 & 0 & 4  \\
0 & 0  & 2  & 0 & 1 & 0 & 12 \\
0 & 3  & 2  & 0 & 0 & 1 & 18 \\
\end{array}
\right]
$$

You may need the following link:

<a href="https://numpy.org/doc/stable/reference/generated/numpy.vstack.html" target="_blank" title="numpy.hstack">numpy.hstack</a>

<a href="https://numpy.org/doc/stable/reference/generated/numpy.vstack.html" target="_blank" title="numpy.vstack">numpy.vstack</a>

In [21]:
A0=np.hstack((np.array([[1]]),-c.transpose(),np.array([[0]])))
A1=np.hstack((np.zeros((3,1)),A,b))
barA=np.vstack((A0,A1))
print(barA)

[[ 1. -3. -5. -0. -0. -0.  0.]
 [ 0.  1.  0.  1.  0.  0.  4.]
 [ 0.  0.  2.  0.  1.  0. 12.]
 [ 0.  3.  2.  0.  0.  1. 18.]]


In [25]:
A3=np.vstack((np.array([[1]]),np.zeros((3,1))))
A4=np.vstack((-c.transpose(),A))
A5=np.vstack((np.array([[0]]),b)) 
barA=np.hstack((A3,A4,A5))
print (barA)

[[ 1. -3. -5. -0. -0. -0.  0.]
 [ 0.  1.  0.  1.  0.  0.  4.]
 [ 0.  0.  2.  0.  1.  0. 12.]
 [ 0.  3.  2.  0.  0.  1. 18.]]


We want to get the $1_{st}$, $4_{th}$, $5_{th}$, $6_{th}$ colunmns of  
$$\left[
\begin{array}{ccccccc}
1 & -3 & -5 & 0 & 0 & 0 & 0  \\
0 & 1  & 0  & 1 & 0 & 0 & 4  \\
0 & 0  & 2  & 0 & 1 & 0 & 12 \\
0 & 3  & 2  & 0 & 0 & 1 & 18 \\
\end{array}
\right]$$
in order to produce the basis matrix 
$$
B=\left[
\begin{array}{cccc}
1  & 0 & 0& 0 \\
0  & 1 & 0 & 0 \\
0  & 0 & 1 & 0 \\
0  & 0 & 0 & 1 \\
\end{array}
\right]
$$

In [28]:
B=np.zeros((m+1,m+1)) #基本產生B的方式
B_index=[0,3,4,5]
for j in range (len(B_index)):
    for i in range (m):
        B[i,j]=barA[i,B_index[j]]
print(B)

[[ 1. -0. -0. -0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  0.]]


In [29]:
B_index=[0,3,4,5] #用python的指令產生B的方式
B=barA[:,B_index]
print(B)

[[ 1. -0. -0. -0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


Transfer 
$$
\left[
\begin{array}{ccccccc}
1 & -3 & -5 & 0 & 0 & 0 & 0  \\
0 & 1  & 0  & 1 & 0 & 0 & 4  \\
0 & 0  & 2  & 0 & 1 & 0 & 12 \\
0 & 3  & 2  & 0 & 0 & 1 & 18 \\
\end{array}
\right]
$$
into the following form:
$$
\left[
\begin{array}{ccccccc}
1 & -3 & 0 & 0 & 5/2 & 0 & 30  \\
0 & 1  & 0  & 1 & 0 & 0 & 4  \\
0 & 0  & 1  & 0 & 1/2 & 0 & 6 \\
0 & 3  & 0  & 0 & -1 & 1 & 6 \\
\end{array}
\right]
$$
Then we obtain 

<img src="table004004.png">
<center>
</center>

In [30]:
B_index=[0,3,4,5]
N_index=[1,2]
B_index=[0,3,2,5]
N_index=[1,4]
B=barA[:,B_index]
print(B)
tabular=np.linalg.inv(B).dot(barA)
print(tabular)

[[ 1. -0. -5. -0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  2.  0.]
 [ 0.  0.  2.  1.]]
[[ 1.  -3.   0.   0.   2.5  0.  30. ]
 [ 0.   1.   0.   1.   0.   0.   4. ]
 [ 0.   0.   1.   0.   0.5  0.   6. ]
 [ 0.   3.   0.   0.  -1.   1.   6. ]]


In [39]:
for i in range(m+1):
    for j in range (n+2):
        print("%.2f" % tabular[i,j],end="")
    print(" ")

1.00-3.00-5.000.000.000.000.00 
0.001.000.001.000.000.004.00 
0.000.002.000.001.000.0012.00 
0.003.002.000.000.001.0018.00 


In [41]:
B_index=[0,3,4,5]
N_index=[1,2]
B=barA[:,B_index]
#print(B)
tabular=np.linalg.inv(B).dot(barA)
#print(tabular)
for i in range(m+1):
    for j in range (n+2):
        print("%.2f" % tabular[i,j],end="")
    print(" ")
minValue=float("inf") 
p=-1  #p為加入的變數
for j in range(1,n+1):
    if tabular[0,j] < minValue:
        minValue = tabular[0,j]
        p=j
    print(tabular[0,j])
print(minValue,p)

minValue=float("inf") 
q=1  #p為拿出的變數
for j in range(1,n+1):
    if tabular[0,j] < minValue:
        minValue = tabular[0,j]
        q=B_index[i]
    print(tabular[0,j])
print(minValue,p)

1.00-3.00-5.000.000.000.000.00 
0.001.000.001.000.000.004.00 
0.000.002.000.001.000.0012.00 
0.003.002.000.000.001.0018.00 
-3.0
-5.0
0.0
0.0
0.0
-5.0 2
-3.0
-5.0
0.0
0.0
0.0
-5.0 2
