We consider the following LP:

$$
(P)\begin{array}{rl}
\max & 3x_1+5x_2\\
s.t.   & x_1+x_3=4\\
       & 2x_2+x_4=12\\
       & 3x_1+2x_2+x_5=18\\
       & x_1,x_2,x_3,x_4,x_5 \geq 0\\
\end{array}
$$

The feasible domain can be plotted as 

<img src="figure001.png">
<center>
The feasible domain in $\mathbb{R}^2$
</center>

All possible basic feasible solutions are computed.
<center>
    Extreme Points in $\mathbb{R}^{5}$
</center>
$$
\begin{array}{lll}
(0,0,4,12,18), &x_1=0, x_2=0\\
(0,6,4,0,6),   &x_1=0, x_4=0\\
(0,9,4,-6,0),  &x_1=0, x_5=0\\
(2,6,2,0,0),   &x_4=0, x_5=0\\
(4,0,0,12,6),  &x_2=0, x_3=0\\
(4,3,0,12,0),  &x_3=0, x_5=0\\
(4,6,0,0,-6),  &x_3=0, x_4=0\\
(6,0,-2,6,0),  &x_2=0, x_5=0\\
\end{array}
$$

The iteration of simplex method is given by 
$$
\begin{array}{lll}
(4,0,0,12,6),  & x_2=0, x_3=0\\
&\Downarrow\\
(4,3,0,12,0),  & x_3=0, x_5=0\\
&\Downarrow\\
(2,6,2,0,0),   & x_4=0, x_5=0\\
\end{array}
$$

<img src="table004003.png">
<center>
</center>

<img src="table004004.png">
<center>
</center>

<img src="table004005.png">
<center>
</center>

<img src="table004006.png">
<center>
</center>

Original Form:
$$
\begin{array}{cccccccccccccccccc}
z:   & z & - & 3x_1& - & 5x_2 &   &     &   &     &   &     & = & 0\\
x_3: &   &   &  x_1&   &      & + & {x_3} &   &     &   &     & = & 4\\
x_2: &   &   &     & + & {2x_2} &   &     & + & x_4 &   &     & = & 12 \\
x_5: &   &   & 3x_1& + & {2x_2} &   &     &   &     & + & {x_5} & = & 18\\
\end{array}
$$

Simplified Form
$$
\begin{array}{cccccccccccccccccc}
z:   & {z} & - & 3x_1& +  & {0x_2} & + &{0x_3} & + & \displaystyle\frac{5}{2}x_4    & + & {0x_5} & = & 30\\
x_3: & {0z}&   &  x_1& +  & {0x_2} & + &{ x_3} &   &                      & + & {0x_5} & = & 4\\
x_2: & {0z}&   &     & +  & {x_2 } & + &{0x_3} & + & \displaystyle\frac{1}{2}x_4    & + & {0x_5} & = & 6 \\
x_5: & {0z}&   & 3x_1& +  & {0x_2} & + &{0x_3} & -  & x_4                 & + & {x_5 }& = & 6\\
\end{array}
$$

<img src="table004007.png">
<center>
</center>

Suppose $x_1$ and $x_4$ are set to zero. Want to know the values of $z$, $x_2$, $x_3$, $x_5$.

Original Form:
$$
\begin{array}{cccccccccccccccccc}
z:   & z & - & 3x_1& - & 5x_2 &   &     &   &     &   &     & = & 0\\
x_3: &   &   &  x_1&   &      & + & {x_3} &   &     &   &     & = & 4\\
x_2: &   &   &     & + & {2x_2} &   &     & + & x_4 &   &     & = & 12 \\
x_5: &   &   & 3x_1& + & {2x_2} &   &     &   &     & + & {x_5} & = & 18\\
\end{array}
$$
Simplified Form
$$
\begin{array}{cccccccccccccccccc}
z:   & {z} & - & 3x_1& +  & {0x_2} & + &{0x_3} & + & \displaystyle\frac{5}{2}x_4    & + & {0x_5} & = & 30\\
x_3: & {0z}&   &  x_1& +  & {0x_2} & + &{ x_3} &   &                      & + & {0x_5} & = & 4\\
x_2: & {0z}&   &     & +  & {x_2 } & + &{0x_3} & + & \displaystyle\frac{1}{2}x_4    & + & {0x_5} & = & 6 \\
x_5: & {0z}&   & 3x_1& +  & {0x_2} & + &{0x_3} & -  & x_4                 & + & {x_5 }& = & 6\\
\end{array}
$$

<ul>
  <li> These two systems of linear equations are coincided.
  <li> The objective value $30$ is directly obtained from the second system.
  <li> We can observe how we reduce the value of $z$.
  <li> If we fix $x_4$ by $0$ and increase $x_1$, then there is a convenient way for updating the value $x_1$.
      </ul>

Matrix Representation for Tabular Form

Let
$$
\bar{A}=
\left[
\begin{array}{ccc}
1 & -{\bf c}^t & 0\\
{\bf 0} & A & {\bf b}\\
\end{array}
\right]
=\left[
\begin{array}{ccccccc}
1 & -3 & -5 & 0 & 0 & 0 & 0  \\
0 & 1  & 0  & 1 & 0 & 0 & 4  \\
0 & 0  & 2  & 0 & 1 & 0 & 12 \\
0 & 3  & 2  & 0 & 0 & 1 & 18 \\
\end{array}
\right]\hbox{ and }
\bar{B}=\left[
\begin{array}{ccc}
1 & -{\bf c}_{B}^t \\
{\bf 0} & B\\
\end{array}
\right].
$$
Set
$$
%\hbox{ and }
B=\left[
\begin{array}{cccc}
 1 & 0 & 0 \\
 0 & 2 & 0 \\
 0 & 2 & 1 \\
\end{array}
\right]
\hbox{ and }
B^{-1}=\left[
\begin{array}{cccc}
 1 & 0 & 0 \\
 0 & 1/2 & 0 \\
 0 & -1 & 1 \\
\end{array}
\right].
$$
Then
$$
\bar{B}^{-1}=
\left[
\begin{array}{ccc}
1 & {\bf c}_{B}^tB^{-1} \\
{\bf 0} & B^{-1}\\
\end{array}
\right]=
\left[
\begin{array}{cccc}
1  & 0 & 5/2& 0 \\
0  & 1 & 0 & 0 \\
0  & 0 & 1/2 & 0 \\
0  & 0 & -1 & 1 \\
\end{array}
\right].
$$

$$
\bar{B}^{-1}\bar{A}=
\left[
\begin{array}{ccc}
1 & {\bf c}_{B}^tB^{-1} \\
{\bf 0} & B^{-1}\\
\end{array}
\right]
\left[
\begin{array}{ccc}
1 & -{\bf c}^t & 0\\
{\bf 0} & A & {\bf b}\\
\end{array}
\right]
=
\left[
\begin{array}{ccc}
1 & -{\bf c}^t+{\bf c}_{B}^{t}B^{-1}A & {\bf c}_{B}^{t}B^{-1}{\bf b}\\
{\bf 0} & B^{-1}A & B^{-1}{\bf b}\\
\end{array}
\right]
$$
$$
=\left[
\begin{array}{ccccccc}
1 & -3 & 0 & 0 & 5/2 & 0 & 30  \\
0 & 1  & 0  & 1 & 0 & 0 & 4  \\
0 & 0  & 1  & 0 & 1/2 & 0 & 6 \\
0 & 3  & 0  & 0 & -1 & 1 & 6 \\
\end{array}
\right]({\hbox{Please verify it by yourself once}})
$$

In [10]:
import numpy as np
import sympy

<img src="table004003.png">
<center>
</center>

$$
(P)\begin{array}{rl}
\max & 3x_1+5x_2\\
s.t.   & x_1+x_3=4\\
       & 2x_2+x_4=12\\
       & 3x_1+2x_2+x_5=18\\
       & x_1,x_2,x_3,x_4,x_5 \geq 0\\
\end{array}
$$

Declare a numpy array c=np.zeros((n,1)) to store the cost vector 
$$
\left[\begin{array}{c}
3\\
5\\
0\\
0\\
0\\
\end{array}
\right]
$$

In [11]:
n=5
c=np.zeros((n,1))
c[0,0]=3
c[1,0]=5
c[2,0]=0
c[3,0]=0
c[4,0]=0
print(c)

[[3.]
 [5.]
 [0.]
 [0.]
 [0.]]


Declare a numpy array b=np.zeros((m,1)) to store the right-hand-side vector  
$$
\left[\begin{array}{c}
4\\
12\\
18\\
\end{array}
\right]
$$

In [12]:
m=3
b=np.zeros((m,1))
b[0,0]=4
b[1,0]=12
b[2,0]=18
#c[3,0]=0
#c[4,0]=0
print(b)

[[ 4.]
 [12.]
 [18.]]


Declare a numpy array A=np.zeros((m,n)) to store the constraint matrix

$$
\left[\begin{array}{c}
1 & 0 & 1 & 0 & 0\\
0 & 2 & 0 & 1 & 0\\
3 & 2 & 0 & 0 & 1\\
\end{array}
\right]
$$

In [13]:
m,n=3,5
A=np.zeros((m,n))
A[0,0]=1
A[1,0]=0
A[2,0]=3

A[0,1]=0
A[1,1]=2
A[2,1]=2

A[0,2]=1
A[1,2]=0
A[2,2]=0

A[0,3]=0
A[1,3]=1
A[2,3]=0

A[0,4]=0
A[1,4]=0
A[2,4]=1

#c[3,0]=0
#c[4,0]=0
print(A)

[[1. 0. 1. 0. 0.]
 [0. 2. 0. 1. 0.]
 [3. 2. 0. 0. 1.]]


In [14]:
A=np.array([[1,0,1,0,0],[0,2,0,1,0],[3,2,0,0,1]])
print(A)

[[1 0 1 0 0]
 [0 2 0 1 0]
 [3 2 0 0 1]]


In order to obtain the matrix in 
<img src="table004003.png">
Use $A$, $b$, $c$ to construct the augmented matrix:
$$
\left[
\begin{array}{ccccccc}
1 & -3 & -5 & 0 & 0 & 0 & 0  \\
0 & 1  & 0  & 1 & 0 & 0 & 4  \\
0 & 0  & 2  & 0 & 1 & 0 & 12 \\
0 & 3  & 2  & 0 & 0 & 1 & 18 \\
\end{array}
\right]
$$

You may need the following link:

<a href="https://numpy.org/doc/stable/reference/generated/numpy.vstack.html" target="_blank" title="numpy.hstack">numpy.hstack</a>

<a href="https://numpy.org/doc/stable/reference/generated/numpy.vstack.html" target="_blank" title="numpy.vstack">numpy.vstack</a>

In [15]:
A0=np.hstack((np.array([[1]]),-c.transpose(),np.array([[0]])))
A1=np.hstack((np.zeros((3,1)),A,b))
barA=np.vstack((A0,A1))
print(barA)

[[ 1. -3. -5. -0. -0. -0.  0.]
 [ 0.  1.  0.  1.  0.  0.  4.]
 [ 0.  0.  2.  0.  1.  0. 12.]
 [ 0.  3.  2.  0.  0.  1. 18.]]


We want to get the $1_{st}$, $4_{th}$, $5_{th}$, $6_{th}$ colunmns of  
$$\left[
\begin{array}{ccccccc}
1 & -3 & -5 & 0 & 0 & 0 & 0  \\
0 & 1  & 0  & 1 & 0 & 0 & 4  \\
0 & 0  & 2  & 0 & 1 & 0 & 12 \\
0 & 3  & 2  & 0 & 0 & 1 & 18 \\
\end{array}
\right]$$
in order to produce the basis matrix 
$$
B=\left[
\begin{array}{cccc}
1  & 0 & 0& 0 \\
0  & 1 & 0 & 0 \\
0  & 0 & 1 & 0 \\
0  & 0 & 0 & 1 \\
\end{array}
\right]
$$

In [16]:
B_index=[0,3,4,5]
B=barA[:,B_index]
print(B)
print(barA)

[[ 1. -0. -0. -0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
[[ 1. -3. -5. -0. -0. -0.  0.]
 [ 0.  1.  0.  1.  0.  0.  4.]
 [ 0.  0.  2.  0.  1.  0. 12.]
 [ 0.  3.  2.  0.  0.  1. 18.]]


Transfer 
$$
\left[
\begin{array}{ccccccc}
1 & -3 & -5 & 0 & 0 & 0 & 0  \\
0 & 1  & 0  & 1 & 0 & 0 & 4  \\
0 & 0  & 2  & 0 & 1 & 0 & 12 \\
0 & 3  & 2  & 0 & 0 & 1 & 18 \\
\end{array}
\right]
$$
into the following form:
$$
\left[
\begin{array}{ccccccc}
1 & -3 & 0 & 0 & 5/2 & 0 & 30  \\
0 & 1  & 0  & 1 & 0 & 0 & 4  \\
0 & 0  & 1  & 0 & 1/2 & 0 & 6 \\
0 & 3  & 0  & 0 & -1 & 1 & 6 \\
\end{array}
\right]
$$
Then we obtain 

<img src="table004004.png">
<center>
</center>

In [17]:
B_index=[0,3,2,5]
B=barA[:,B_index]
print(B)
tabular=np.linalg.inv(B).dot(barA)
print(tabular)

[[ 1. -0. -5. -0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  2.  0.]
 [ 0.  0.  2.  1.]]
[[ 1.  -3.   0.   0.   2.5  0.  30. ]
 [ 0.   1.   0.   1.   0.   0.   4. ]
 [ 0.   0.   1.   0.   0.5  0.   6. ]
 [ 0.   3.   0.   0.  -1.   1.   6. ]]


<img src="table004006.png">
<center>
</center>

In [18]:
B_index=[0,3,4,5]
N_index=[1,2]
B=barA[:,B_index]
print(B)
tabular=np.linalg.inv(B).dot(barA)
print(tabular)
B_index=[0,3,2,5]
N_index=[1,4]
B=barA[:,B_index]
print(B)
tabular=np.linalg.inv(B).dot(barA)
print(tabular)

[[ 1. -0. -0. -0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
[[ 1. -3. -5.  0.  0.  0.  0.]
 [ 0.  1.  0.  1.  0.  0.  4.]
 [ 0.  0.  2.  0.  1.  0. 12.]
 [ 0.  3.  2.  0.  0.  1. 18.]]
[[ 1. -0. -5. -0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  2.  0.]
 [ 0.  0.  2.  1.]]
[[ 1.  -3.   0.   0.   2.5  0.  30. ]
 [ 0.   1.   0.   1.   0.   0.   4. ]
 [ 0.   0.   1.   0.   0.5  0.   6. ]
 [ 0.   3.   0.   0.  -1.   1.   6. ]]


In [19]:
B_index=[0,3,2,1]
N_index=[5,4]
B=barA[:,B_index]
print(B)
tabular=np.linalg.inv(B).dot(barA)
print(tabular)

[[ 1. -0. -5. -3.]
 [ 0.  1.  0.  1.]
 [ 0.  0.  2.  0.]
 [ 0.  0.  2.  3.]]
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   1.50000000e+00  1.00000000e+00  3.60000000e+01]
 [ 0.00000000e+00  5.55111512e-17  0.00000000e+00  1.00000000e+00
   3.33333333e-01 -3.33333333e-01  2.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  0.00000000e+00
   5.00000000e-01  0.00000000e+00  6.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00
  -3.33333333e-01  3.33333333e-01  2.00000000e+00]]


<img src="table004008.png">
<center>
</center>

In [20]:
print(tabular)

[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   1.50000000e+00  1.00000000e+00  3.60000000e+01]
 [ 0.00000000e+00  5.55111512e-17  0.00000000e+00  1.00000000e+00
   3.33333333e-01 -3.33333333e-01  2.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  0.00000000e+00
   5.00000000e-01  0.00000000e+00  6.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00
  -3.33333333e-01  3.33333333e-01  2.00000000e+00]]


In [21]:
i,j=0,6
print("%.2f" % tabular[i,j])

36.00


<img src="table004008.png">
<center>
</center>

In [22]:
for i in range(m+1):
    for j in range(n+2):
        print(" %.2f " % tabular[i,j],end="")
    print(" ")

 1.00  0.00  0.00  0.00  1.50  1.00  36.00  
 0.00  0.00  0.00  1.00  0.33  -0.33  2.00  
 0.00  0.00  1.00  0.00  0.50  0.00  6.00  
 0.00  1.00  0.00  0.00  -0.33  0.33  2.00  


In [23]:
#############STEP 1#######################

B_index=[0,3,4,5]
N_index=[1,2]
B=barA[:,B_index]
print(B)
tabular=np.linalg.inv(B).dot(barA)
for i in range(m+1):
    for j in range(n+2):
        print(" %.2f " % tabular[i,j],end="")
    print(" ")
#############STEP 2#######################
B_index=[0,3,2,5]
print(B_index)
N_index=[1,4]
B=barA[:,B_index]
print(B)
tabular=np.linalg.inv(B).dot(barA)
for i in range(m+1):
    for j in range(n+2):
        print(" %.2f " % tabular[i,j],end="")
    print(" ")
#############STEP 3#######################
B_index=[0,3,2,1]
N_index=[5,4]
B=barA[:,B_index]
print(B)
tabular=np.linalg.inv(B).dot(barA)
for i in range(m+1):
    for j in range(n+2):
        print(" %.2f " % tabular[i,j],end="")
    print(" ")

[[ 1. -0. -0. -0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
 1.00  -3.00  -5.00  0.00  0.00  0.00  0.00  
 0.00  1.00  0.00  1.00  0.00  0.00  4.00  
 0.00  0.00  2.00  0.00  1.00  0.00  12.00  
 0.00  3.00  2.00  0.00  0.00  1.00  18.00  
[0, 3, 2, 5]
[[ 1. -0. -5. -0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  2.  0.]
 [ 0.  0.  2.  1.]]
 1.00  -3.00  0.00  0.00  2.50  0.00  30.00  
 0.00  1.00  0.00  1.00  0.00  0.00  4.00  
 0.00  0.00  1.00  0.00  0.50  0.00  6.00  
 0.00  3.00  0.00  0.00  -1.00  1.00  6.00  
[[ 1. -0. -5. -3.]
 [ 0.  1.  0.  1.]
 [ 0.  0.  2.  0.]
 [ 0.  0.  2.  3.]]
 1.00  0.00  0.00  0.00  1.50  1.00  36.00  
 0.00  0.00  0.00  1.00  0.33  -0.33  2.00  
 0.00  0.00  1.00  0.00  0.50  0.00  6.00  
 0.00  1.00  0.00  0.00  -0.33  0.33  2.00  


In [24]:
#############STEP 1#######################
B_index=[0,3,4,5]
N_index=[1,2]
B=barA[:,B_index]
#print(B)
tabular=np.linalg.inv(B).dot(barA)
for i in range(m+1):
    for j in range(n+2):
        print(" %.2f " % tabular[i,j],end="")
    print(" ")
for j in range(1,n+1):
    print(tabular[0,j])

 1.00  -3.00  -5.00  0.00  0.00  0.00  0.00  
 0.00  1.00  0.00  1.00  0.00  0.00  4.00  
 0.00  0.00  2.00  0.00  1.00  0.00  12.00  
 0.00  3.00  2.00  0.00  0.00  1.00  18.00  
-3.0
-5.0
0.0
0.0
0.0


In [25]:
#############STEP 1#######################
B_index=[0,3,4,5]
N_index=[1,2]
B=barA[:,B_index]
#print(B)
tabular=np.linalg.inv(B).dot(barA)
for i in range(m+1):
    for j in range(n+2):
        print(" %.2f " % tabular[i,j],end="")
    print(" ")
minValue=float("inf")
p=-1
for j in range(1,n+1):
    if tabular[0,j]<minValue:
        minValue=tabular[0,j]
        p=j
    print(tabular[0,j])
print(minValue,p)

minValue=float("inf")
q=-1
for i in range(1,m+1):
    if tabular[i,p]>0:
        if (tabular[i,n+1]/tabular[i,p]) < minValue:
            minValue = tabular[i,n+1]/tabular[i,p]
            q=B_index[i]
print(q)

 1.00  -3.00  -5.00  0.00  0.00  0.00  0.00  
 0.00  1.00  0.00  1.00  0.00  0.00  4.00  
 0.00  0.00  2.00  0.00  1.00  0.00  12.00  
 0.00  3.00  2.00  0.00  0.00  1.00  18.00  
-3.0
-5.0
0.0
0.0
0.0
-5.0 2
4


In [26]:
print(B_index)
l=0
while l<len(B_index):
    if B_index[l]==q:
        B_index[l]=p
        break
    l=l+1
print(B_index)

[0, 3, 4, 5]
[0, 3, 2, 5]


In [27]:
print(sympy.nsimplify(0.3))
print(sympy.nsimplify(0.33))
print(sympy.nsimplify(0.333))

3/10
33/100
333/1000


In [39]:
#############STEP 1#######################
B_index=[0,3,2,5]
N_index=[1,2]
B=barA[:,B_index]
#print(B)
tabular=np.linalg.inv(B).dot(barA)
print("Basic Vars",end=" ")
print("Z",end=" ")
for i in range(n):
    print("X_%d" % (i+1),end=" ")
print("RHS",end=" ")
print(" ")
for i in range(1):
    for j in range(n+2):
            print(sympy.nsimplify(tabular[i,j]),end=" ")
    print(" ")
for i in range(1,m+1):
    print("x_%d" % B_index[i],end=" ")
    for j in range(n+2):
            print(sympy.nsimplify(tabular[i,j]),end=" ")
    print(" ")
minValue=float("inf")
p=-1
for j in range(1,n+1):
    if tabular[0,j]<minValue:
        minValue=tabular[0,j]
        p=j
    print(tabular[0,j])
print(minValue,p)

minValue=float("inf")
q=-1
for i in range(1,m+1):
    if tabular[i,p]>0:
        if (tabular[i,n+1]/tabular[i,p]) < minValue:
            minValue = tabular[i,n+1]/tabular[i,p]
            q=B_index[i]
print(q)
l=0
while l<len(B_index):
    if B_index[l]==q:
        B_index[l]=p
        break
    l=l+1
print(B_index)
#############STEP 2#######################
#B_index=[0,3,4,5]
#N_index=[1,2]
B=barA[:,B_index]
#print(B)
tabular=np.linalg.inv(B).dot(barA)
for i in range(m+1):
    for j in range(n+2):
        #print(" %.2f " % tabular[i,j],end="")
        if abs(tabular[i,j])<1e-8:
            print("0",end=" ")
        else:
            print(sympy.nsimplify(tabular[i,j]),end=" ")
    print(" ")
minValue=float("inf")
p=-1
for j in range(1,n+1):
    if tabular[0,j]<minValue:
        minValue=tabular[0,j]
        p=j
    print(tabular[0,j])
print(minValue,p)

minValue=float("inf")
q=-1
for i in range(1,m+1):
    if tabular[i,p]>0:
        if (tabular[i,n+1]/tabular[i,p]) < minValue:
            minValue = tabular[i,n+1]/tabular[i,p]
            q=B_index[i]
print(q)
l=0
while l<len(B_index):
    if B_index[l]==q:
        B_index[l]=p
        break
    l=l+1
print(B_index)
#############STEP 3#######################
#B_index=[0,3,2,5]
#N_index=[1,2]
B=barA[:,B_index]
#print(B)
tabular=np.linalg.inv(B).dot(barA)
for i in range(m+1):
    for j in range(n+2):
        #print(" %.2f " % tabular[i,j],end="")
        if abs(tabular[i,j])<1e-8:
            print("0",end=" ")
        else:
            print(sympy.nsimplify(tabular[i,j]),end=" ")
    print(" ")
minValue=float("inf")
p=-1
for j in range(1,n+1):
    if tabular[0,j]<minValue:
        minValue=tabular[0,j]
        p=j
    print(tabular[0,j])
print(minValue,p)

minValue=float("inf")
q=-1
for i in range(1,m+1):
    if tabular[i,p]>0:
        if (tabular[i,n+1]/tabular[i,p]) < minValue:
            minValue = tabular[i,n+1]/tabular[i,p]
            q=B_index[i]
print(q)
l=0
while l<len(B_index):
    if B_index[l]==q:
        B_index[l]=p
        break
    l=l+1
print(B_index)

Basic Vars Z X_1 X_2 X_3 X_4 X_5 RHS  
1 -3 0 0 5/2 0 30  
x_3 0 1 0 1 0 0 4  
x_2 0 0 1 0 1/2 0 6  
x_5 0 3 0 0 -1 1 6  
-3.0
0.0
0.0
2.5
0.0
-3.0 1
5
[0, 3, 2, 1]
1 0 0 0 3/2 1 36  
0 0 0 1 1/3 -1/3 2  
0 0 1 0 1/2 0 6  
0 1 0 0 -1/3 1/3 2  
0.0
0.0
0.0
1.5
1.0
0.0 1
1
[0, 3, 2, 1]
1 0 0 0 3/2 1 36  
0 0 0 1 1/3 -1/3 2  
0 0 1 0 1/2 0 6  
0 1 0 0 -1/3 1/3 2  
0.0
0.0
0.0
1.5
1.0
0.0 1
1
[0, 3, 2, 1]


In [43]:
#############STEP 1#######################
print("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">")
print("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">")
print("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\"></script>")
B_index=[0,3,2,5]
N_index=[1,2]
B=barA[:,B_index]
#print(B)
tabular=np.linalg.inv(B).dot(barA)
print("<table class=table table-bordered table-hover>")
print("<tbody>")
print("<tr>")
print("<th style='text-align:center'>Basic Vars</th>",end=" ")
print("<th style='text-align:center'>Z</th>",end=" ")
for i in range(n):
    print("<th style='text-align:center'>X_%d</th>" % (i+1),end=" ")
print("<th style='text-align:center'>RHS</th>",end=" ")
print(" ")
print("</tr>")
print("<tr>")
for i in range(1):
    #print("<td>Z</td>=")
    for j in range(n+2):
            print("<td>",sympy.nsimplify(tabular[i,j]),"</td>",end=" ")
    print(" ")
    print("</tr>")

for i in range(1,m+1):
    print("<tr>")
    print("<td>x_%d</td>" % B_index[i],end=" ")
    for j in range(n+2):
            print("<td>",sympy.nsimplify(tabular[i,j]),"</td>",end=" ")
    print(" ")
    print("</tr>")
print("</tbody>")
print("</table>")
minValue=float("inf")
p=-1
for j in range(1,n+1):
    if tabular[0,j]<minValue:
        minValue=tabular[0,j]
        p=j
    print(tabular[0,j])
print(minValue,p)

minValue=float("inf")
q=-1
for i in range(1,m+1):
    if tabular[i,p]>0:
        if (tabular[i,n+1]/tabular[i,p]) < minValue:
            minValue = tabular[i,n+1]/tabular[i,p]
            q=B_index[i]
print(q)
l=0
while l<len(B_index):
    if B_index[l]==q:
        B_index[l]=p
        break
    l=l+1
print(B_index)

<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
<table class=table table-bordered table-hover>
<tbody>
<tr>
<th style='text-align:center'>Basic Vars</th> <th style='text-align:center'>Z</th> <th style='text-align:center'>X_1</th> <th style='text-align:center'>X_2</th> <th style='text-align:center'>X_3</th> <th style='text-align:center'>X_4</th> <th style='text-align:center'>X_5</th> <th style='text-align:center'>RHS</th>  
</tr>
<tr>
<td> 1 </td> <td> -3 </td> <td> 0 </td> <td> 0 </td> <td> 5/2 </td> <td> 0 </td> <td> 30 </td>  
</tr>
<tr>
<td>x_3</td> <td> 0 </td> <td> 1 </td> <td> 0 </td> <td> 1 </td> <td> 0 </td> <td> 0 </td> <td> 4 </td>  
</tr>
<tr>
<td>x_2</td> <td> 0 </td> <td> 0 </td> <td> 1 </td> <td> 0 </td> <td> 1/2 </td> <td> 0 </td> <td> 6 </td>  
</tr

<!DOCTYPE html>
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>

<div class="container mt-3">
  <h2>Tabular</h2>
  <p>hehe:</p>              
  <table class="table table-bordered table-hover">     
      <tr>
        <th>Basic Vars </th><th> Z </th><th> x_1 </th><th> x_2 </th><th> x_3 </th><th> x_4 </th><th> x_5 </th><th> RHS </th>
      </tr>
      <tr>
      	<td>Z </td> <td>1 </td> <td>-3 </td> <td>0 </td> <td>0 </td> <td>5/2 </td> <td>0 </td> <td>30 </td>
      <tr> 
      <tr>
<td>x_3 </td> <td>0 </td> <td>1 </td> <td>0 </td> <td>1 </td> <td>0 </td> <td>0 </td> <td>4 </td>
</tr>
      <tr>
<td>x_2 </td> <td>0</td> <td> 0</td> <td> 1</td> <td> 0</td> <td> 1/2</td> <td> 0 </td> <td>6  </td>
</tr>
      <tr>
<td>x_5</td> <td> 0 </td> <td>3</td> <td> 0</td> <td> 0</td> <td> -1</td> <td> 1</td> <td> 6  </td>
      </tr>
      
   
  </table>
</div>

</body>
</html>


<img src="NO1219.jpg">