Determine $\alpha_{P}$ and $\alpha_{D}$ as follows:
$$
\alpha_{P}=\min\left\{1,\min_{(\Delta {\bf x})_{j}<0} \left\{\frac{r x^k_{j}}{-(\Delta {\bf x})_{j}}\right\}  \right\}
$$
$$
\alpha_{D}=\min\left\{1,\min_{(\Delta {\bf s})_{j}<0} \left\{\frac{r s^k_{j}}{-(\Delta {\bf s})_{j}}\right\}  \right\}
$$

In [1]:
import numpy as np 
def determineStepSize(x,d,r):
    n=len(d)
    stepSize=float("inf")
    for i in range(n):
        if d[i] < 0 and stepSize>-x[i]/d[i]:
            stepSize=-x[i]/d[i]
    stepSize=min([1,r*stepSize])
    return stepSize
A=[[2,1,1,0],[1,3,0,1]]

b=[[70],[90]]
c=[[-40],[-60],[0],[0]]
A=np.array(A)
b=np.array(b)
c=np.array(c)
mu=[]
mu.append(10)
x0,y0,s0=[[1],[2],[3],[4]],[[9],[10]],[[5],[6],[7],[8]]
e=np.ones((4,1))

mu_0=10
r=0.6
epsilon=1e-2
k=0
while mu[k]>epsilon*mu_0:
#for k in range(100):
    x0=np.array(x0)
    y0=np.array(y0)
    s0=np.array(s0)
    solution=np.vstack((x0,y0,s0))

    X=np.diag(x0[:,0])
    S=np.diag(s0[:,0])

    r1=b-A.dot(x0)
    r2=c-A.transpose().dot(y0)+s0
    r3=mu[k]*e-X.dot(S).dot(e)
    residual=np.vstack((r1,r2,r3))

    A1=np.hstack((A,np.zeros((2,2)),np.zeros((2,4))))
    A2=np.hstack((np.zeros((4,4)),A.transpose(),np.identity(4)))
    A3=np.hstack((S,np.zeros((4,2)),X))
    barA=np.vstack((A1,A2,A3))

    NewtonDirection=np.linalg.inv(barA).dot(residual)
    delta_x=NewtonDirection[0:4,0].reshape(4,1)
    delta_y=NewtonDirection[4:6,0].reshape(2,1)
    delta_s=NewtonDirection[6:10,0].reshape(4,1)
    
    stepSizeX=determineStepSize(x0,delta_x,r)
    stepSizeS=determineStepSize(s0,delta_s,r)
    x0=x0+stepSizeX*delta_x
    y0=y0+stepSizeS*delta_y
    s0=s0+stepSizeS*delta_s
    #mu[k+1]=(1/10)*x0.transpose().dot(s0)/4#complementary condition
    mu.append((1/10)*x0.transpose().dot(s0)/4)
    print("mu is ",mu[k+1])
    print("stepSizeX is ",stepSizeX)
    print("stepSizeS is ",stepSizeS)
    print('k=',k)
    print(x0)
    print(y0)
    print(s0)
    k=k+1

mu is  [[2.15394067]]
stepSizeX is  [0.30366806]
stepSizeS is  [0.03738637]
k= 0
[[6.17712393]
 [9.07088428]
 [4.70595567]
 [1.6       ]]
[[9.55238132]
 [9.53989589]]
[[2.        ]
 [3.35099837]
 [6.37284593]
 [8.38533137]]
mu is  [[1.48550141]]
stepSizeX is  [0.1722607]
stepSizeS is  [0.13190174]
k= 1
[[10.13887878]
 [11.22899925]
 [ 2.18122069]
 [ 0.64      ]]
[[7.29523623]
 [6.46363965]]
[[ 0.8       ]
 [ 2.32984798]
 [ 8.21060477]
 [11.30929854]]
mu is  [[0.93399135]]
stepSizeX is  [0.17972322]
stepSizeS is  [0.24387344]
k= 2
[[13.1335359 ]
 [13.07453118]
 [ 0.87248828]
 [ 0.29228657]]
[[2.6699572 ]
 [1.49981986]]
[[ 0.32      ]
 [ 1.2743232 ]
 [13.05911788]
 [17.45484585]]
mu is  [[0.53541413]]
stepSizeX is  [0.21062091]
stepSizeS is  [0.35897671]
k= 3
[[15.60555352]
 [14.92752404]
 [ 0.34899531]
 [ 0.12810427]]
[[-2.65150779]
 [-4.3647515 ]]
[[ 0.128     ]
 [ 0.5346981 ]
 [22.11004963]
 [29.0469    ]]
mu is  [[0.30738332]]
stepSizeX is  [0.24222488]
stepSizeS is  [0.4271749]
k= 4

In [2]:
import numpy as np 
def determineStepSize(x,d,r):
    n=len(d)
    stepSize=float("inf")
    for i in range(n):
        if d[i] < 0 and stepSize>-x[i]/d[i]:
            stepSize=-x[i]/d[i]
    stepSize=min([1,r*stepSize])
    return stepSize

A=[[2,1,1,0],[1,3,0,1]]

b=[[70],[90]]
c=[[-40],[-60],[0],[0]]
A=np.array(A)
b=np.array(b)
c=np.array(c)
mu=[]
mu.append(10)

x0=[[0],[0],[70],[110],[0],[0],[15],[60],[5]]
A=np.zeros((5,9))
b=np.zeros((5,1))
A[0,0],A[0,1],A[0,2],b[0,0]=1,1,1,70
A[1,3],A[1,4],A[1,5],b[1,0]=1,1,1,110
A[2,6],A[2,7],A[2,8],b[2,0]=1,1,1,80
A[3,0],A[3,3],A[3,6],b[3,0]=1,1,1,125
A[4,1],A[4,4],A[4,7],b[4,0]=1,1,1,60
c=np.zeros((9,1))
c[0,0],c[1,0],c[2,0]=162,121.5,82.8
c[3,0],c[4,0],c[5,0]=93.6,108,75
c[6,0],c[7,0],c[8,0]=158.4,100.8,100.8
#A[5,?]

#x0,y0,s0=[[1],[2],[3],[4]],[[9],[10]],[[5],[6],[7],[8]]
#e=np.ones((4,1))
x0=[[20],[20],[30],[90],[10],[10],[15],[30],[35]]
y0=[[0],[0],[0],[0],[0]]
s0=[[1],[2],[3],[4],[5],[6],[7],[8],[9]]
e=np.ones((9,1))

mu_0=10
r=0.6
epsilon=1e-2
k=0
while mu[k]>epsilon*mu_0:
#for k in range(100):
    x0=np.array(x0)
    y0=np.array(y0)
    s0=np.array(s0)
    solution=np.vstack((x0,y0,s0))

    X=np.diag(x0[:,0])
    S=np.diag(s0[:,0])

    r1=b-A.dot(x0)
    print(np.linalg.norm(r1))
    r2=c-A.transpose().dot(y0)+s0
    print(np.linalg.norm(r2))
    r3=mu[k]*e-X.dot(S).dot(e)
    print(np.linalg.norm(r3))
    residual=np.vstack((r1,r2,r3))

    A1=np.hstack((A,np.zeros((5,5)),np.zeros((5,9))))
    A2=np.hstack((np.zeros((9,9)),A.transpose(),np.identity(9)))
    A3=np.hstack((S,np.zeros((9,5)),X))
    barA=np.vstack((A1,A2,A3))

    NewtonDirection=np.linalg.inv(barA).dot(residual)
    delta_x=NewtonDirection[0:9,0].reshape(9,1)
    delta_y=NewtonDirection[9:14,0].reshape(5,1)
    delta_s=NewtonDirection[14:23,0].reshape(9,1)
    
    stepSizeX=determineStepSize(x0,delta_x,r)
    stepSizeS=determineStepSize(s0,delta_s,r)
    x0=x0+stepSizeX*delta_x
    y0=y0+stepSizeS*delta_y
    s0=s0+stepSizeS*delta_s
    #mu[k+1]=(1/10)*x0.transpose().dot(s0)/4#complementary condition
    mu.append((1/10)*x0.transpose().dot(s0)/9)
    print("mu is ",mu[k+1])
    print("stepSizeX is ",stepSizeX)
    print("stepSizeS is ",stepSizeS)
    print('k=',k)
    print(x0)
    #print(y0)
    #print(s0)
    k=k+1


0.0
359.56819937252516
537.5406961337904
mu is  [[11.32604198]]
stepSizeX is  [0.07507032]
stepSizeS is  [0.13339491]
k= 0
[[ 10.67273115]
 [ 21.19932817]
 [ 38.12794068]
 [100.53754647]
 [  4.        ]
 [  5.46245353]
 [ 13.78972238]
 [ 34.80067183]
 [ 31.40960579]]
2.4613922385709617e-14
314.1130506484657
427.0245064785445
mu is  [[9.12793938]]
stepSizeX is  [0.0924874]
stepSizeS is  [0.15522558]
k= 1
[[  6.81565559]
 [ 14.15411342]
 [ 49.03023099]
 [106.01167907]
 [  1.6       ]
 [  2.38832093]
 [ 12.17266533]
 [ 44.24588658]
 [ 23.58144808]]
3.4809342861069267e-14
277.57781395202676
363.3332765115126
mu is  [[7.90468809]]
stepSizeX is  [0.09364895]
stepSizeS is  [0.19194714]
k= 2
[[  6.4892202 ]
 [  5.66164537]
 [ 57.84913444]
 [107.87529045]
 [  0.82934313]
 [  1.29536642]
 [ 10.63548936]
 [ 53.5090115 ]
 [ 15.85549914]]
4.4938668397781776e-14
253.05996091723492
333.94120026250505
mu is  [[7.8497682]]
stepSizeX is  [0.08445758]
stepSizeS is  [0.37082049]
k= 3
[[  6.09146456]
 [  2

In [3]:
import random
x0=[]
for i in range(20):
    x0.append([random.randint(1,100)])
y0=[]
for i in range(8):
    y0.append([random.randint(1,100)])
s0=[]
for i in range(20):
    #s0.append([random.randint(1,100)])
    s0.append([1])

x0=np.array(x0)
y0=np.array(y0)
s0=np.array(s0)

A=np.zeros((8,20))
b=np.zeros((8,1))
A[0,0],A[0,1],A[0,2],A[0,3],b[0,0]=1,1,1,1,400
A[1,4],A[1,5],A[1,6],A[1,7],b[1,0]=1,1,1,1,600
A[2,8],A[2,9],A[2,10],A[2,11],b[2,0]=1,1,1,1,400
A[3,12],A[3,13],A[3,14],A[3,15],b[3,0]=1,1,1,1,600
A[4,16],A[4,17],A[4,18],A[4,19],b[4,0]=1,1,1,1,1000

A[5,0],A[5,4],A[5,8],A[5,12],A[5,16],b[5,0]=1,1,1,1,1,600
A[6,1],A[6,5],A[6,9],A[6,13],A[6,17],b[6,0]=1,1,1,1,1,1000
A[7,2],A[7,6],A[7,10],A[7,14],A[7,18],b[7,0]=1,1,1,1,1,800
#A[8,3],A[8,7],A[8,11],A[8,15],A[8,19],b[8,0]=1,1,1,1,1,600

AA=np.zeros((8,20))
AA[0,0],AA[0,1],AA[0,2],AA[0,3],b[0,0]=1,1,1,1,400
AA[1,4],AA[1,5],AA[1,6],AA[1,7],b[1,0]=1,1,1,1,600
AA[2,8],AA[2,9],AA[2,10],AA[2,11],b[2,0]=1,1,1,1,400
AA[3,12],AA[3,13],AA[3,14],AA[3,15],b[3,0]=1,1,1,1,600
AA[4,16],AA[4,17],AA[4,18],AA[4,19],b[4,0]=1,1,1,1,1000

AA[5,0],AA[5,4],AA[5,8],AA[5,12],AA[5,16],b[5,0]=1,1,1,1,1,600
AA[6,1],AA[6,5],AA[6,9],AA[6,13],AA[6,17],b[6,0]=1,1,1,1,1,1000
AA[7,2],AA[7,6],AA[7,10],AA[7,14],AA[7,18],b[7,0]=1,1,1,1,1,800


c=np.zeros((20,1))
c[0,0],c[1,0],c[2,0],c[3,0]=31,45,38,0
c[4,0],c[5,0],c[6,0],c[7,0]=29,41,35,0
c[8,0],c[9,0],c[10,0],c[11,0]=32,46,40,0
c[12,0],c[13,0],c[14,0],c[15,0]=28,42,600,0
c[16,0],c[17,0],c[18,0],c[19,0]=29,43,600,0


print(A.dot(x0)-b)
print(c.transpose().dot(x0))

mu=[]
mu.append(10)
e=np.ones((20,1))

mu_0=10
r=0.6
epsilon=1e-6
k=0
while mu[k]>epsilon*mu_0:
    mu[k]=mu_0*(1/10)**k
    x0=np.array(x0)
    y0=np.array(y0)
    s0=np.array(s0)
    solution=np.vstack((x0,y0,s0))

    X=np.diag(x0[:,0])
    S=np.diag(s0[:,0])

    r1=b-A.dot(x0)
    r2=c-A.transpose().dot(y0)+s0
    r3=mu[k]*e-X.dot(S).dot(e)
    residual=np.vstack((r1,r2,r3))

    A1=np.hstack((A,np.zeros((8,8)),np.zeros((8,20))))
    A2=np.hstack((np.zeros((20,20)),A.transpose(),np.identity(20)))
    A3=np.hstack((S,np.zeros((20,8)),X))
    barA=np.vstack((A1,A2,A3))
    
    #NewtonDirection=np.linalg.inv(barA.transpose().dot(barA)).dot(barA.transpose()).dot(residual)
    NewtonDirection=np.linalg.inv(barA).dot(residual)
    delta_x=NewtonDirection[0:20,0].reshape(20,1)
    delta_y=NewtonDirection[20:28,0].reshape(8,1)
    delta_s=NewtonDirection[28:48,0].reshape(20,1)
    
    stepSizeX=determineStepSize(x0,delta_x,r)
    stepSizeS=determineStepSize(s0,delta_s,r)
    x0=x0+stepSizeX*delta_x
    y0=y0+stepSizeS*delta_y
    s0=s0+stepSizeS*delta_s
    #mu[k+1]=(1/10)*x0.transpose().dot(s0)/4#complementary condition
    mu.append((1/10)*x0.transpose().dot(s0)/20)
    #print("mu is ",mu[k+1])
    #print("stepSizeX is ",stepSizeX)
    #print("stepSizeS is ",stepSizeS)
    #print('k=',k)
    print(x0)
    #print(y0)
    #print(s0)
    k=k+1
print("x0 is ", x0)
r1=A.dot(x0)-b
print("the finial cost is %f"% (c.transpose().dot(x0)))
print("r1 is ",r1)

[[-165.]
 [-369.]
 [-199.]
 [-405.]
 [-717.]
 [-323.]
 [-673.]
 [-577.]]
[[81159.]]
[[61.44157329]
 [22.9215157 ]
 [85.00754402]
 [65.92768409]
 [60.85441625]
 [72.935407  ]
 [80.26130018]
 [17.61602206]
 [35.36756629]
 [64.21208235]
 [ 6.98112898]
 [94.79901086]
 [55.53211176]
 [83.48722402]
 [ 0.8       ]
 [55.91289706]
 [64.3883107 ]
 [84.66054305]
 [50.99323264]
 [84.25423696]]
[[56.04153704]
 [20.68522603]
 [99.45604153]
 [59.48916242]
 [55.60702926]
 [66.18100423]
 [94.85063908]
 [15.86409003]
 [35.22321969]
 [63.04350849]
 [10.29135189]
 [93.25235287]
 [56.6442878 ]
 [83.87986856]
 [ 0.35452274]
 [55.77069449]
 [74.79935256]
 [95.9512036 ]
 [20.39729306]
 [94.77215291]]
[[ 54.0728315 ]
 [ 19.95012299]
 [104.68043203]
 [ 57.49443401]
 [ 53.62661586]
 [ 64.10671052]
 [100.693203  ]
 [ 15.25223289]
 [ 34.70095637]
 [ 62.01069164]
 [ 13.49109689]
 [ 92.24189925]
 [ 57.31298683]
 [ 84.61330881]
 [  0.16509295]
 [ 55.84871635]
 [ 79.63143387]
 [101.2048219 ]
 [  8.15891722]
 [ 99.2099

In [20]:
A=np.zeros((8,20))
b=np.zeros((8,1))
A[0,0],A[0,1],A[0,2],A[0,3],b[0,0]=1,1,1,1,400
A[1,4],A[1,5],A[1,6],A[1,7],b[1,0]=1,1,1,1,600
A[2,8],A[2,9],A[2,10],A[2,11],b[2,0]=1,1,1,1,400
A[3,12],A[3,13],A[3,14],A[3,15],b[3,0]=1,1,1,1,600
A[4,16],A[4,17],A[4,18],A[4,19],b[4,0]=1,1,1,1,1000

A[5,0],A[5,4],A[5,8],A[5,12],A[5,16],b[5,0]=1,1,1,1,1,600
A[6,1],A[6,5],A[6,9],A[6,13],A[6,17],b[6,0]=1,1,1,1,1,1000
A[7,2],A[7,6],A[7,10],A[7,14],A[7,18],b[7,0]=1,1,1,1,1,800
#A[8,3],A[8,7],A[8,11],A[8,15],A[8,19],b[8,0]=1,1,1,1,1,600


c=np.zeros((20,1))
c[0,0],c[1,0],c[2,0],c[3,0]=31,45,38,0
c[4,0],c[5,0],c[6,0],c[7,0]=29,41,35,0
c[8,0],c[9,0],c[10,0],c[11,0]=32,46,40,0
c[12,0],c[13,0],c[14,0],c[15,0]=28,42,600,0
c[16,0],c[17,0],c[18,0],c[19,0]=29,43,600,0


mu_0=10
r=0.6
epsilon=1e-6
problem="LP"
################################################################
def IPM(A,b,c,problem,r,epsilon,mu_0):
    m=len(A)
    n=len(A[0,:])
    print(m,n)
    import random
    x0=[]
    for i in range(20):
        x0.append([random.randint(1,100)])
    y0=[]
    for i in range(8):
        y0.append([random.randint(1,100)])
    s0=[]
    for i in range(20):
        #s0.append([random.randint(1,100)])
        s0.append([1])

    x0=np.array(x0)
    y0=np.array(y0)
    s0=np.array(s0)

    mu=[]
    mu.append(mu_0)
    if problem=="LP":
        e=np.ones((n,1))
    #elif problem=="SOCP":

    else:
        e=np.ones((n,1))

    k=0
    while mu[k]>epsilon*mu_0:
        mu[k]=mu_0*(1/10)**k
        x0=np.array(x0)
        y0=np.array(y0)
        s0=np.array(s0)
        solution=np.vstack((x0,y0,s0))

        if problem == "LP":
            X=np.diag(x0[:,0])
            S=np.diag(s0[:,0])
        else:
            X=np.diag(x0[:,0])
            S=np.diag(s0[:,0])

        r1=b-A.dot(x0)
        r2=c-A.transpose().dot(y0)+s0
        r3=mu[k]*e-X.dot(S).dot(e)
        residual=np.vstack((r1,r2,r3))

        A1=np.hstack((A,np.zeros((m,m)),np.zeros((m,n))))
        A2=np.hstack((np.zeros((n,n)),A.transpose(),np.identity(n)))
        A3=np.hstack((S,np.zeros((n,m)),X))
        barA=np.vstack((A1,A2,A3))

        #NewtonDirection=np.linalg.inv(barA.transpose().dot(barA)).dot(barA.transpose()).dot(residual)
        NewtonDirection=np.linalg.inv(barA).dot(residual)
        delta_x=NewtonDirection[0:n,0].reshape(n,1)
        delta_y=NewtonDirection[n:m+n,0].reshape(m,1)
        delta_s=NewtonDirection[m+n:m+n+n,0].reshape(n,1)

        if problem=="LP":
            stepSizeX=determineStepSize(x0,delta_x,r)
            stepSizeS=determineStepSize(s0,delta_s,r)
        else:
            stepSizeX=determineStepSize(x0,delta_x,r)
            stepSizeS=determineStepSize(s0,delta_s,r)

        x0=x0+stepSizeX*delta_x
        y0=y0+stepSizeS*delta_y
        s0=s0+stepSizeS*delta_s
        #mu[k+1]=(1/10)*x0.transpose().dot(s0)/4#complementary condition
        mu.append((1/10)*x0.transpose().dot(s0)/20)
        #print("mu is ",mu[k+1])
        #print("stepSizeX is ",stepSizeX)
        #print("stepSizeS is ",stepSizeS)
        #print('k=',k)
        print(x0)
        #print(y0)
        #print(s0)
        k=k+1
    print("x0 is ", x0)
    r1=A.dot(x0)-b
    print("the finial cost is %f"% (c.transpose().dot(x0)))
    print("r1 is ",r1)

In [21]:
IPM(A,b,c,problem,r,epsilon,mu_0)

8 20
[[88.20627229]
 [47.68687925]
 [93.82808156]
 [ 4.53398846]
 [66.06563866]
 [32.38218772]
 [54.05678327]
 [83.05657026]
 [21.67837271]
 [36.68577392]
 [11.86630062]
 [19.24770879]
 [23.90030747]
 [ 3.80591039]
 [13.00360915]
 [22.11733682]
 [76.64755214]
 [70.68460691]
 [ 7.2       ]
 [74.65477492]]
[[84.52942226]
 [46.24593377]
 [99.52638335]
 [ 4.34053366]
 [64.25777316]
 [32.05208493]
 [59.8358084 ]
 [80.26656039]
 [21.3346314 ]
 [36.58868979]
 [13.35187203]
 [18.92810147]
 [28.70385556]
 [ 4.73388639]
 [ 5.20144366]
 [25.44239813]
 [78.42791079]
 [73.51338807]
 [ 3.48721282]
 [75.55844491]]
[[ 82.81616673]
 [ 45.82755435]
 [102.5393914 ]
 [  4.29624487]
 [ 63.14014842]
 [ 32.21569064]
 [ 63.81723598]
 [ 79.07972876]
 [ 21.23208043]
 [ 36.93227882]
 [ 14.47576709]
 [ 19.13144074]
 [ 31.81700039]
 [  5.83869305]
 [  2.08057746]
 [ 27.05827279]
 [ 79.8820244 ]
 [ 76.40433405]
 [  1.62125044]
 [ 76.97229397]]
[[ 81.68840295]
 [ 45.84293123]
 [105.59892325]
 [  4.3484472 ]
 [ 62.17

In [22]:
A=np.zeros((5,9))
b=np.zeros((5,1))
A[0,0],A[0,1],A[0,2],b[0,0]=1,1,1,70
A[1,3],A[1,4],A[1,5],b[1,0]=1,1,1,110
A[2,6],A[2,7],A[2,8],b[2,0]=1,1,1,80
A[3,0],A[3,3],A[3,6],b[3,0]=1,1,1,125
A[4,1],A[4,4],A[4,7],b[4,0]=1,1,1,60
c=np.zeros((9,1))
c[0,0],c[1,0],c[2,0]=162,121.5,82.8
c[3,0],c[4,0],c[5,0]=93.6,108,75
c[6,0],c[7,0],c[8,0]=158.4,100.8,100.8

problem="LP"
mu_0=10
r=0.6
epsilon=1e-6
problem="LP"


In [23]:
IPM(A,b,c,problem,r,epsilon,mu_0)

5 9


ValueError: shapes (5,9) and (20,1) not aligned: 9 (dim 1) != 20 (dim 0)