In [72]:
import numpy as np 
A=[[2,1,1,0],[1,3,0,1]]
b=[[70],[90]]
c=[[-40],[-60],[0],[0]]
A=np.array(A)
b=np.array(b)
c=np.array(c)

x0,y0,s0=[[1],[2],[3],[4]],[[9],[10]],[[5],[6],[7],[8]]

In [73]:
I=np.identity(4)
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [74]:
s0=np.array(s0)
S=np.diag(s0[:,0])
print(S)

[[5 0 0 0]
 [0 6 0 0]
 [0 0 7 0]
 [0 0 0 8]]


In [75]:
x0=np.array(x0)
X=np.diag(x0[:,0])
print(X)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [76]:
np.vstack((np.hstack((A,np.zeros((2,2)))),np.hstack((np.zeros((4,4)),A.transpose()))))

array([[2., 1., 1., 0., 0., 0.],
       [1., 3., 0., 1., 0., 0.],
       [0., 0., 0., 0., 2., 1.],
       [0., 0., 0., 0., 1., 3.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [77]:
A1=np.hstack((A,np.zeros((2,2)),np.zeros((2,4))))
A2=np.hstack((np.zeros((4,4)),A.transpose(),I))
A3=np.hstack((S,np.zeros((4,2)),X))

In [78]:
barA=np.vstack((A1,A2,A3))
print(barA)

[[2. 1. 1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 3. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 2. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 3. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 1.]
 [5. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 6. 0. 0. 0. 0. 0. 2. 0. 0.]
 [0. 0. 7. 0. 0. 0. 0. 0. 3. 0.]
 [0. 0. 0. 8. 0. 0. 0. 0. 0. 4.]]


In [79]:
x0,y0,s0=[[1],[2],[3],[4]],[[9],[10]],[[5],[6],[7],[8]]

x0=np.array(x0)
y0=np.array(y0)
s0=np.array(s0)
e=np.ones((4,1))
mu=100
X=np.diag(x0[:,0])
S=np.diag(s0[:,0])
r1=b-A.dot(x0)
r2=c-A.transpose().dot(y0)+s0
r3=mu*e-X.dot(S).dot(e)
residual=np.vstack((r1,r2,r3))
solution=np.vstack((x0,y0,s0))
print(residual)

[[ 63.]
 [ 79.]
 [-63.]
 [-93.]
 [ -2.]
 [ -2.]
 [ 95.]
 [ 88.]
 [ 79.]
 [ 68.]]


In [80]:
np.linalg.inv(barA).dot(residual)

array([[ 19.79800499],
       [ 19.77805486],
       [  3.62593516],
       [ -0.13216958],
       [-19.87281796],
       [-19.26433915],
       [ -3.99002494],
       [-15.33416459],
       [ 17.87281796],
       [ 17.26433915]])

In [81]:
residual+np.linalg.inv(barA).dot(residual)

array([[ 82.79800499],
       [ 98.77805486],
       [-59.37406484],
       [-93.13216958],
       [-21.87281796],
       [-21.26433915],
       [ 91.00997506],
       [ 72.66583541],
       [ 96.87281796],
       [ 85.26433915]])

In [82]:
mu=[10,0.1,0.001,0.00001,0.0000001,0.000000001]
stepSizeX=[1,1,1,1,1,1]
stepSizeS=[1,0.255739448,0.244416903,0.245570101,0.263017218]
print(mu)
print(stepSizeX)
print(stepSizeS)

[10, 0.1, 0.001, 1e-05, 1e-07, 1e-09]
[1, 1, 1, 1, 1, 1]
[1, 0.255739448, 0.244416903, 0.245570101, 0.263017218]


In [83]:
x1=solution[1:4,0]
y1=solution[4:6,0]
s1=solution[6:10,0]
print(x1,y1,s1)

[2 3 4] [ 9 10] [5 6 7 8]


In [84]:
mu=[10,0.1,0.001,0.00001,0.0000001,0.000000001,0,0,0,0,0,0,0,0,0,0,0]
mu={}
mu[0]=10
stepSizeX=[1,1,1,1,1,1]
stepSizeS=[1,0.255739448,0.244416903,0.240642829,0.245570101,0.263017218]

x0,y0,s0=[[1],[2],[3],[4]],[[9],[10]],[[5],[6],[7],[8]]
e=np.ones((4,1))

def determineStepSize(x,d,r):
    n=len(d)
    stepSize=float("inf")
    for i in range(n):
        if d[i] < 0 and stepSize>-x[i]/d[i]:
            stepSize=-x[i]/d[i]
    stepSize=min([1,r*stepSize])
    return stepSize

mu_0=10
r=0.6
epsilon=1e-4
k=0

while mu[k]>0.01:
#for k in range(100):
    x0=np.array(x0)
    y0=np.array(y0)
    s0=np.array(s0)
    solution=np.vstack((x0,y0,s0))

    X=np.diag(x0[:,0])
    S=np.diag(s0[:,0])

    r1=b-A.dot(x0)
    r2=c-A.transpose().dot(y0)+s0
    r3=mu[k]*e-X.dot(S).dot(e)
    residual=np.vstack((r1,r2,r3))

    A1=np.hstack((A,np.zeros((2,2)),np.zeros((2,4))))
    A2=np.hstack((np.zeros((4,4)),A.transpose(),I))
    A3=np.hstack((S,np.zeros((4,2)),X))
    barA=np.vstack((A1,A2,A3))

    NewtonDirection=np.linalg.inv(barA).dot(residual)
    delta_x=NewtonDirection[0:4,0].reshape(4,1)
    delta_y=NewtonDirection[4:6,0].reshape(2,1)
    delta_s=NewtonDirection[6:10,0].reshape(4,1)
    #solution=solution+NewtonDirection
    
    stepSizeX=determineStepSize(x0,delta_x,r)
    stepSizeS=determineStepSize(s0,delta_s,r)
    x0=x0+stepSizeX*delta_x
    y0=y0+stepSizeS*delta_y
    s0=s0+stepSizeS*delta_s
    mu[k+1]=(1/10)*x0.transpose().dot(s0)/4#complementary condition
    
    print("mu is ",mu[k+1][0,0])
    print("stepSizeX is ",stepSizeX)
    print("stepSizeS is ",stepSizeS)
    print('k=',k)
    print(x0)
    print(y0)
    print(s0)
    k=k+1

mu is  2.153940672227939
stepSizeX is  [0.30366806]
stepSizeS is  [0.03738637]
k= 0
[[6.17712393]
 [9.07088428]
 [4.70595567]
 [1.6       ]]
[[9.55238132]
 [9.53989589]]
[[2.        ]
 [3.35099837]
 [6.37284593]
 [8.38533137]]
mu is  1.4855014071433645
stepSizeX is  [0.1722607]
stepSizeS is  [0.13190174]
k= 1
[[10.13887878]
 [11.22899925]
 [ 2.18122069]
 [ 0.64      ]]
[[7.29523623]
 [6.46363965]]
[[ 0.8       ]
 [ 2.32984798]
 [ 8.21060477]
 [11.30929854]]
mu is  0.9339913522661111
stepSizeX is  [0.17972322]
stepSizeS is  [0.24387344]
k= 2
[[13.1335359 ]
 [13.07453118]
 [ 0.87248828]
 [ 0.29228657]]
[[2.6699572 ]
 [1.49981986]]
[[ 0.32      ]
 [ 1.2743232 ]
 [13.05911788]
 [17.45484585]]
mu is  0.5354141308072011
stepSizeX is  [0.21062091]
stepSizeS is  [0.35897671]
k= 3
[[15.60555352]
 [14.92752404]
 [ 0.34899531]
 [ 0.12810427]]
[[-2.65150779]
 [-4.3647515 ]]
[[ 0.128     ]
 [ 0.5346981 ]
 [22.11004963]
 [29.0469    ]]
mu is  0.30738331681280123
stepSizeX is  [0.24222488]
stepSizeS 

Determine $\alpha_{P}$ and $\alpha_{D}$ as follows:
$$
\alpha_{P}=\min\left\{1,\min_{(\Delta {\bf x})_{j}<0} \left\{\frac{r x^k_{j}}{-(\Delta {\bf x})_{j}}\right\}  \right\}
$$
$$
\alpha_{D}=\min\left\{1,\min_{(\Delta {\bf s})_{j}<0} \left\{\frac{r s^k_{j}}{-(\Delta {\bf s})_{j}}\right\}  \right\}
$$

In [85]:
def determineStepSize(x,d,r):
    n=len(d)
    stepSize=float("inf")
    for i in range(n):
        if d[i] < 0 and stepSize<-x[i]/d[i]:
            stepSize=-x[i]/d[i]
    stepSize=min([1,r*stepSize])
    return stepSize
