In [61]:
import numpy as np
A=[[1,-2,-1,0],[-1,-1,0,-1]]
b=[[-4],[-4]]
c=[[-1],[-3],[0],[0]]
A=np.array(A)
b=np.array(b)
c=np.array(c)

x0,y0,s0=[[1],[2],[3],[4]],[[9],[10]],[[5],[6],[7],[8]]

a = np.array((1,2,3))
b = np.array((4,5,6))
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [62]:
a = np.array((1,2,3))
b = np.array((4,5,6))
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [63]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [65]:
np.zeros((4, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [66]:
A.transpose()

array([[ 1, -1],
       [-2, -1],
       [-1,  0],
       [ 0, -1]])

In [67]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [68]:
s0=np.array(s0)
np.diag(s0[:,0])

array([[5, 0, 0, 0],
       [0, 6, 0, 0],
       [0, 0, 7, 0],
       [0, 0, 0, 8]])

In [69]:
np.hstack((A,np.zeros((2, 2))))

array([[ 1., -2., -1.,  0.,  0.,  0.],
       [-1., -1.,  0., -1.,  0.,  0.]])

In [70]:
np.hstack((np.zeros((4, 4)),A.transpose()))

array([[ 0.,  0.,  0.,  0.,  1., -1.],
       [ 0.,  0.,  0.,  0., -2., -1.],
       [ 0.,  0.,  0.,  0., -1.,  0.],
       [ 0.,  0.,  0.,  0.,  0., -1.]])

In [71]:
np.vstack((np.hstack((A,np.zeros((2, 2)))),np.hstack((np.zeros((4, 4)),A.transpose()))))

array([[ 1., -2., -1.,  0.,  0.,  0.],
       [-1., -1.,  0., -1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1., -1.],
       [ 0.,  0.,  0.,  0., -2., -1.],
       [ 0.,  0.,  0.,  0., -1.,  0.],
       [ 0.,  0.,  0.,  0.,  0., -1.]])

In [72]:
s0=np.array(s0)
S=np.diag(s0[:,0])
print(S)

[[5 0 0 0]
 [0 6 0 0]
 [0 0 7 0]
 [0 0 0 8]]


In [73]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [74]:
x0=np.array(x0)
X=np.diag(x0[:,0])
print(X)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [85]:
A1=np.hstack((A,np.zeros((2, 2)),np.zeros((2, 4))))
A2=np.hstack((np.zeros((4, 4)),A.transpose(),np.identity(4)))
A3=np.hstack((S,np.zeros((4, 2)),X))
barA=np.vstack((A1,A2,A3))

In [86]:
x0=np.array(x0)
y0=np.array(y0)
s0=np.array(s0)
solution=np.vstack((x0,y0,s0))
print(solution)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 9]
 [10]
 [ 5]
 [ 6]
 [ 7]
 [ 8]]


In [87]:
A=[[1,-2,-1,0],[-1,-1,0,-1]]
b=[[-4],[-4]]
c=[[-1],[-3],[0],[0]]
A=np.array(A)
b=np.array(b)
c=np.array(c)

x0,y0,s0=[[1],[2],[3],[4]],[[9],[10]],[[5],[6],[7],[8]]

In [88]:
x0=np.array(x0)
y0=np.array(y0)
s0=np.array(s0)
e=np.ones((4,1))
X=np.diag(x0[:,0])
S=np.diag(s0[:,0])
mu=100
r1=b-A.dot(x0)
r2=c-A.transpose().dot(y0)+s0
r3=mu*e-X.dot(S).dot(e)
residual=np.vstack((r1,r2,r3))
print(residual)

[[ 2.]
 [ 3.]
 [ 5.]
 [31.]
 [16.]
 [18.]
 [95.]
 [88.]
 [79.]
 [68.]]


In [95]:
NewtonDirection=np.linalg.inv(barA).dot(residual)

In [104]:
solution=solution+np.linalg.inv(barA).dot(solution)
print(solution)

[[  -3.04145082]
 [   3.88207587]
 [ -82.1045886 ]
 [ -10.48143056]
 [ 131.45394143]
 [  16.45480467]
 [-304.98635021]
 [ 187.65996051]
 [ 414.60935106]
 [ 132.4922164 ]]


In [107]:
x0,y0,s0=[[1],[2],[3],[4]],[[9],[10]],[[5],[6],[7],[8]]
mu=[10,0.1,0.001,0.00001,0.0000001,0.000000001]
x0=np.array(x0)
y0=np.array(y0)
s0=np.array(s0)
e=np.ones((4,1))
solution=np.vstack((x0,y0,s0))
##################################################
k=0
X=np.diag(x0[:,0])
S=np.diag(s0[:,0])
r1=b-A.dot(x0)
r2=c-A.transpose().dot(y0)+s0
r3=mu[k]*e-X.dot(S).dot(e)
residual=np.vstack((r1,r2,r3))
##################################################
A1=np.hstack((A,np.zeros((2, 2)),np.zeros((2, 4))))
A2=np.hstack((np.zeros((4, 4)),A.transpose(),np.identity(4)))
A3=np.hstack((S,np.zeros((4, 2)),X))
barA=np.vstack((A1,A2,A3))
##################################################
NewtonDirection=np.linalg.inv(barA).dot(residual)
solution=solution+NewtonDirection
x0=solution[0:4,0].reshape(4,1)
y0=solution[4:6,0].reshape(2,1)
s0=solution[6:10,0].reshape(4,1)
print(x0,y0,s0)

[[ 1.60921053]
 [ 3.19473684]
 [-0.78026316]
 [-0.80394737]] [[-1.84605263]
 [-3.89210526]] [[ 6.95394737]
 [ 1.41578947]
 [12.15394737]
 [12.10789474]]


In [111]:
stepSizeX=[1,1,1,1,1,1]
stepSizeS=[1,0.255739448,0.244416903,0.240642829,0.245570101,0.263017218]
x0,y0,s0=[[1],[2],[3],[4]],[[9],[10]],[[5],[6],[7],[8]]
mu=[10,0.1,0.001,0.00001,0.0000001,0.000000001]
x0=np.array(x0)
y0=np.array(y0)
s0=np.array(s0)
e=np.ones((4,1))
for k in range(6):
    print("k=%d"%k)
    X=np.diag(x0[:,0])
    S=np.diag(s0[:,0])
    r1=b-A.dot(x0)
    r2=c-A.transpose().dot(y0)+s0
    r3=mu[k]*e-X.dot(S).dot(e)
    residual=np.vstack((r1,r2,r3))
    ##################################################
    A1=np.hstack((A,np.zeros((2, 2)),np.zeros((2, 4))))
    A2=np.hstack((np.zeros((4, 4)),A.transpose(),np.identity(4)))
    A3=np.hstack((S,np.zeros((4, 2)),X))
    barA=np.vstack((A1,A2,A3))
    ##################################################
    NewtonDirection=np.linalg.inv(barA).dot(residual)
    
    delta_x=NewtonDirection[0:4,0].reshape(4,1)
    delta_y=NewtonDirection[4:6,0].reshape(2,1)
    delta_s=NewtonDirection[6:10,0].reshape(4,1)
    x0=x0+stepSizeX[k]*delta_x
    y0=y0+stepSizeS[k]*delta_y
    s0=s0+stepSizeS[k]*delta_s
    
    print(x0,y0,s0)

k=0
[[ 1.60921053]
 [ 3.19473684]
 [-0.78026316]
 [-0.80394737]] [[-1.84605263]
 [-3.89210526]] [[ 6.95394737]
 [ 1.41578947]
 [12.15394737]
 [12.10789474]]
k=1
[[1.50391381]
 [2.21836743]
 [1.06717896]
 [0.27771877]] [[-0.26376703]
 [-4.9553616 ]] [[ 5.30780827]
 [ 1.17237741]
 [16.37236828]
 [13.14573987]]
k=2
[[ 1.03018218]
 [ 3.13679002]
 [-1.24339786]
 [-0.1669722 ]] [[ 0.4617128 ]
 [-5.02457931]] [[ 4.41930687]
 [ 0.76730512]
 [21.03506254]
 [15.07838904]]
k=3
[[1.77003312]
 [2.13798141]
 [1.4940703 ]
 [0.09198547]] [[ 1.37110341]
 [-5.44501635]] [[ 2.59207404]
 [ 0.64145407]
 [27.11749799]
 [17.07732922]]
k=4
[[ 0.86542405]
 [ 3.21879417]
 [-1.57216429]
 [-0.08421823]] [[ 1.38247552]
 [-4.46199692]] [[ 2.28085194]
 [ 0.40430014]
 [34.12481882]
 [20.9168969 ]]
k=5
[[1.85370639]
 [2.07549338]
 [1.70271962]
 [0.07080023]] [[ 1.76419515]
 [-4.16493731]] [[ 0.99588114]
 [ 0.33573298]
 [43.84556823]
 [25.54187852]]


k= 0
mu ==10.000000000
stepSizeX == 1.000000000
stepSizeS == 1.000000000
k= 1
mu is 0.100000000
stepSizeX is 1.000000000
stepSizeS is 0.255739448
k= 2
mu is 0.001000000
stepSizeX is 1.000000000
stepSizeS is 0.244416903
k= 3
mu is 0.000010000
stepSizeX is 1.000000000
stepSizeS is 0.240642829
k= 4
mu is 0.000000100
stepSizeX is 1.000000000
stepSizeS is 0.245570101
k= 5
mu == 0.000000001
stepSizeX == 1.000000000
stepSizeS == 0.263017218
